name: build package

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
  
jobs:
  build_macos:
    name: 'macos'
    runs-on: macos-13
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.11.0-dev.4191+1bf16b172
    - uses: hendrikmuhs/ccache-action@v1.2
    - name: build
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
    - name: install system dependencies
      run: |
        bash tools/mac.install.brew.deps.sh
        pip install Jinja2
    - name: install gn
      run: |
        tar xf deps/gn/gn-mac-amd64.zip -C tools/
        export PATH=$PATH:$PWD/tools
    - name: fetch v8 dependencies
      run: cd deps && bash ../tools/fetch.v8.deps.sh
    - name: check
      run: |
        /usr/bin/clang -v
        brew --prefix llvm@15
    - name: build release
      run: |
        zig build \
          -Doptimize=ReleaseFast \
          -Dprep-staging=true \
          -Drelease-tarball=true \
          -Dv8-toolchain=$(brew --prefix llvm@15) \
          -DCC=$(brew --prefix llvm@15)/clang \ 
          -DCXX=$(brew --prefix llvm@15)/clang++