name: build package

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
  
jobs:
  build_macos:
    name: 'macos'
    runs-on: macos-13
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.11.0-dev.4191+1bf16b172
    - name: install system dependencies
      run: bash tools/mac.install.brew.deps.sh
    - name: install gn
      run: |
        tar xf deps/gn/gn-mac-amd64.zip -C tools/
        export PATH=$PATH:$PWD/tools
    - name: fetch v8 dependencies
      run: cd deps && bash ../tools/fetch.v8.deps.sh
    - name: build release
      run: zig build -Doptimize=ReleaseFast -Dprep-staging=true -Drelease-tarball=true
    
  # build_linux:
  #   name: 'linux'
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: build staging
  #     run: zig build -Dprep-staging=true
  #   - name: build release
  #     run: zig build -Drelease-tarball=true